// this file will be replaced with the following command, added here to avoid compile error
// Code will be generated by "esc -pkg assets -o cmd/server/app/web-console/actual/generated_assets.go -prefix console-web/build console-web/build"

package assets

import (
	"net/http"
)

// should be replaced with actual implementation
func FS(useLocal bool) http.FileSystem {
	return nil
}
