export const DataType = {
  String: "string",
  Number: "number",
  Integer: "integer",
  Float: "float",
  Boolean: "boolean",
  Object: "object",
  ArrayString: "array_string",
  ArrayNumber: "array_number",
  ArrayBoolean: "array_boolean",
  ArrayObject: "array_object",
}

export const FieldType = {
  Text: "text",
  TextArea: "text_area",
  Password: "password",
  Email: "email",
  Number: "number",
  Date: "data",
  Checkbox: "checkbox",
  Labels: "labels",
  KeyValueMap: "key_value_map",
  VariablesMap: "variables_map",
  MixedControlList: "mixed_control_list",
  DynamicListGeneric: "dynamic_list_generic",
  ColorBox: "color_box",
  ThresholdsColor: "thresholds_color",
  DynamicArray: "dynamic_array",
  ConditionsArrayMap: "conditions_array_map",
  Divider: "divider",
  Select: "select",
  SelectTypeAhead: "select_type_ahead",
  SelectTypeAheadMultiple: "select_type_ahead_multiple",
  SelectTypeAheadAsync: "select_type_ahead_async",
  Switch: "switch",
  DatePicker: "date_picker",
  DateRangePicker: "date_range_picker",
  TimePicker: "time_picker",
  TimeRangePicker: "time_range_picker",
  ToggleButtonGroup: "toggle_button_group",
  ScriptEditor: "script_editor",
  SliderSimple: "slider_simple",
  ChartYAxisConfigMap: "chart_y_axis_config_map",
  ChartMixedResourceConfig: "chart_mixed_resource_config",
  PolicyStatements: "policy_statements",
}
